// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxI6qrTQ01p_-oHfDgfILpZJDGL88GH4',
    appId: '1:155995450570:web:b809c9e5dff7e6e8645833',
    messagingSenderId: '155995450570',
    projectId: 'movie-app-7b660',
    authDomain: 'movie-app-7b660.firebaseapp.com',
    storageBucket: 'movie-app-7b660.firebasestorage.app',
    measurementId: 'G-GE3GLRYQ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJd60_GD8MUpSul2wQqmTPg9mayQOLgGI',
    appId: '1:155995450570:android:0a7f6e81d9a45798645833',
    messagingSenderId: '155995450570',
    projectId: 'movie-app-7b660',
    storageBucket: 'movie-app-7b660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjs6wpDpYTWb-3e0thTcqra5mYah1WCyo',
    appId: '1:155995450570:ios:3984b69952ce9ed3645833',
    messagingSenderId: '155995450570',
    projectId: 'movie-app-7b660',
    storageBucket: 'movie-app-7b660.firebasestorage.app',
    iosBundleId: 'hr.algebra.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoxI6qrTQ01p_-oHfDgfILpZJDGL88GH4',
    appId: '1:155995450570:web:95763e52941e2654645833',
    messagingSenderId: '155995450570',
    projectId: 'movie-app-7b660',
    authDomain: 'movie-app-7b660.firebaseapp.com',
    storageBucket: 'movie-app-7b660.firebasestorage.app',
    measurementId: 'G-7RC87NWWWP',
  );
}
