// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:movie_app/data/local/movie_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MovieEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MovieEntityAdapter());
  }
}
